import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import HomeNavigator from "@/components/features/HomeNavigator"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) { 
  
  return (
    <html lang="en">
      <body className={`${inter.className}`}> 
          <HomeNavigator /> 
          {children} 
     </body>
    </html>
  );
}
